### ISSUE TITLE
找回密码，然后登入，失败

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/Shpcoin-dev#12]
![image](https://user-images.githubusercontent.com/44828242/48395094-09f1aa00-e751-11e8-9dc6-c7220276e477.png)
![image](https://user-images.githubusercontent.com/44828242/48395217-82f10180-e751-11e8-9730-34d0414f8364.png)

**Comment by Jvisions** [comment]
我测试没问题啊
