### ISSUE TITLE
认证邮箱，字体，颜色等需要好看一点

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/Shpcoin-dev#13]
![image](https://user-images.githubusercontent.com/44828242/48395620-c6983b00-e752-11e8-8ec2-bd47021b5871.png)

![image](https://user-images.githubusercontent.com/44828242/48397758-bc2d6f80-e759-11e8-9d64-b42e1ae7431a.png)
改成sheepcoin的logo

**Comment by Jvisions** [comment]
商城的网站就是这样的

**Comment by ErisFU** [comment]
![wx20181115-133243](https://user-images.githubusercontent.com/41175757/48532504-a5168b00-e8db-11e8-9be1-0819ab650356.png)
oOK DONE

**Comment by ErisFU** [comment]
![wx20181115-133243](https://user-images.githubusercontent.com/41175757/48532609-10605d00-e8dc-11e8-955c-f74fd287c747.png)
OK done

**Comment by ErisFU** [comment]
![wx20181115-133243](https://user-images.githubusercontent.com/41175757/48596344-a1463f80-e993-11e8-87f7-30e4e88b78bb.png)
logo 图片修改好了
