### ISSUE TITLE
sheepcoin , 注册后显示一个提示框

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/Shpcoin-dev#14]
![image](https://user-images.githubusercontent.com/44828242/48395992-f8f66800-e753-11e8-8ed4-01f9c4d10c79.png)
 金成，我觉得需要这个句子”收不到邮件的话，查看垃圾箱下“ ，帮我添加一下（这个中文句子我自己写的，你帮我改一改）

**Comment by Jvisions** [comment]
只是qq邮箱是存放到垃圾箱的，如果写了查看垃圾箱的话，是不是会掉公司的level呢，之前也不是存到垃圾箱的，可能是我之前测试发的太多导致的，应该可以设置的

**Comment by piaoseeun** [comment]
![image](https://user-images.githubusercontent.com/44828242/48453673-54296880-e7ef-11e8-96aa-c2441d93f195.png)
金成这个参考一下

**Comment by Jvisions** [comment]
好的
