### ISSUE TITLE
首页增加浮动图标，参考图片中的网址

### ISSUE THREAD

**Issue by yellmi1983** [MemberSheep-Project/Shpcoin-dev#16]
![image](https://user-images.githubusercontent.com/29912212/48455958-2f85be80-e7f8-11e8-9249-5185c688cb05.png)

**Comment by ErisFU** [comment]
![wx20181114-135205](https://user-images.githubusercontent.com/41175757/48462770-83060580-e814-11e8-9b92-0c32629ac6ab.png)
OK  done
