### ISSUE TITLE
在name兰，输入好多个字，点击storage按钮，跳转这个页面（最多字数需要限制）

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/Shpcoin-dev#29]
![image](https://user-images.githubusercontent.com/44828242/48754666-72023c00-eccd-11e8-885a-3df18ea8643b.png)
![image](https://user-images.githubusercontent.com/44828242/48754669-762e5980-eccd-11e8-8c32-c229b713c8aa.png)

**Comment by Jvisions** [comment]
这个数据库大小有所限制
