### ISSUE TITLE
layout broken 

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/Shpcoin-dev#4]
![image](https://user-images.githubusercontent.com/44828242/48323404-0255d680-e667-11e8-8fed-db51d031d6ce.png)

网址：http://www.shpcoin.io/Profile_setting/index

**Comment by ErisFU** [comment]
<img width="1148" alt="wx20181112-143105 2x" src="https://user-images.githubusercontent.com/41175757/48330488-a94a6a80-e687-11e8-8702-a55f65b6d960.png">
OK done
