### ISSUE TITLE
  Road Map 

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/Shpcoin-dev#41]
![image](https://user-images.githubusercontent.com/44828242/49278293-4ba78200-f4bf-11e8-8cae-ef31ca77638a.png)

**Comment by ErisFU** [comment]
![2](https://user-images.githubusercontent.com/41175757/49336655-981acb00-f641-11e8-8393-c15db4891105.png)
ok done
![1](https://user-images.githubusercontent.com/41175757/49336656-981acb00-f641-11e8-8a66-866c7e2b028a.png)
