### ISSUE TITLE
Welcome Page 

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/Shpcoin-dev#45]
![image](https://user-images.githubusercontent.com/44828242/49279219-d7221280-f4c1-11e8-9de1-477da6be9fc3.png)

1.添加一个句子,表示倒计时指的是  [later on change to ICO Ends in …]
2.去掉slide bar[later on add back when ICO starts] 
3.或者更换倒计时和幻灯片,"即将到来"或"slide"或"start"或"slide" 
4. 激活怀特语功能或暂时删除直到以后 
5. Sheep coin网站里面的图片换成英文版本的首页图片

**Comment by ErisFU** [comment]
![2](https://user-images.githubusercontent.com/41175757/49336554-5557f380-f63f-11e8-8698-48177e3e1e04.png)
picture ok
