### ISSUE TITLE
 Our Best Team ，Advisor 

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/Shpcoin-dev#46]
![image](https://user-images.githubusercontent.com/44828242/49281158-cde77480-f4c6-11e8-998c-9db3cb706041.png)

**Comment by ErisFU** [comment]
![1](https://user-images.githubusercontent.com/41175757/49335463-d1930c80-f628-11e8-9aef-e816d028606c.png)
OK DONE
