### ISSUE TITLE
首页 按钮需要修改

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/Shpcoin-dev#47]
![image](https://user-images.githubusercontent.com/44828242/49349675-aec72d80-f6e6-11e8-9b10-93787c73c4e0.png)

**Comment by ErisFU** [comment]
![4](https://user-images.githubusercontent.com/41175757/49429092-a48a5980-f7e2-11e8-804a-f28ace014c4b.png)
OK done 首页 按钮需要修改 #47
