### ISSUE TITLE
Sheep coin不要显示中文，请改成“Copyright 2018 (c) Membersheep Company ltd”

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/Shpcoin-dev#48]
![image](https://user-images.githubusercontent.com/44828242/49349803-4d538e80-f6e7-11e8-8af2-5514a0673adf.png)

Copyright 2018 (c) Membersheep Company ltd

**Comment by ErisFU** [comment]
![2](https://user-images.githubusercontent.com/41175757/49355337-1d65b480-f702-11e8-8df9-e897635ed5ff.png)
OK
