### ISSUE TITLE
sheepcoin 手机版 layout broken 

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/Shpcoin-dev#52]
![image](https://user-images.githubusercontent.com/44828242/49355338-1dfe4b00-f702-11e8-932c-9950ed85ac8d.png)

**Comment by ErisFU** [comment]
![3](https://user-images.githubusercontent.com/41175757/49426164-acde9680-f7da-11e8-8ec1-65701d502ccf.png)
OK DONE sheepcoin 手机版 layout broken #52
