### ISSUE TITLE
sheep coin手机版，需要一个关闭的按钮

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/Shpcoin-dev#53]
![image](https://user-images.githubusercontent.com/44828242/49355437-8ea56780-f702-11e8-96ec-ff96c69551c8.png)

**Comment by ErisFU** [comment]
![1](https://user-images.githubusercontent.com/41175757/49426093-71dc6300-f7da-11e8-973c-5e951b815d6c.png)
![1-](https://user-images.githubusercontent.com/41175757/49426094-7274f980-f7da-11e8-840a-01b902cc9c2a.png)
OK DONE sheep coin手机版，需要一个关闭的按钮 #53
