### ISSUE TITLE
Sheep coin手机版，需要一个按钮，就是按钮点击上移到顶部功能

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/Shpcoin-dev#54]
![image](https://user-images.githubusercontent.com/44828242/49355588-4a669700-f703-11e8-9fcd-ec2126715ac8.png)

**Comment by ErisFU** [comment]
![1](https://user-images.githubusercontent.com/41175757/49425573-f62de680-f7d8-11e8-8f04-b2bdf2a9a5fa.png)
![1-](https://user-images.githubusercontent.com/41175757/49425575-f7f7aa00-f7d8-11e8-91a8-22eca21902df.png)
ok done Sheep coin手机版，需要一个按钮，就是按钮点击上移到顶部功能 #54
