### ISSUE TITLE
sheep coin手机版，layout broken 

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/Shpcoin-dev#55]
![image](https://user-images.githubusercontent.com/44828242/49355673-99143100-f703-11e8-9f81-a3c7b78cbefb.png)

**Comment by ErisFU** [comment]
![6](https://user-images.githubusercontent.com/41175757/49423844-b44e7180-f7d3-11e8-963b-43d911758cc6.png)
OK done sheep coin手机版，layout broken #55
