### ISSUE TITLE
sheep coin , 手机版登不进去

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/Shpcoin-dev#56]
![image](https://user-images.githubusercontent.com/44828242/49355737-cbbe2980-f703-11e8-92e6-6dd160f5beaa.png)
![image](https://user-images.githubusercontent.com/44828242/49355743-d11b7400-f703-11e8-9227-c5b4d3aac391.png)

**Comment by longpizi** [comment]
下一版OK
