### ISSUE TITLE
sheep coin手机版，注册页面，2个按钮间距，需要调整

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/Shpcoin-dev#57]
![image](https://user-images.githubusercontent.com/44828242/49356125-961a4000-f705-11e8-98da-33055d35b74e.png)

**Comment by ErisFU** [comment]
![5](https://user-images.githubusercontent.com/41175757/49423283-ec54b500-f7d1-11e8-8809-0d0e343515d9.png)
![5-](https://user-images.githubusercontent.com/41175757/49423285-ef4fa580-f7d1-11e8-973f-1f9b9576c70c.png)
OK done
