### ISSUE TITLE
sheep coin手机版，登入Dashboard页面，显示提示框大小需要调整

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/Shpcoin-dev#58]
![image](https://user-images.githubusercontent.com/44828242/49356398-9a932880-f706-11e8-89e9-27851e565843.png)

**Comment by ErisFU** [comment]
![4](https://user-images.githubusercontent.com/41175757/49422630-95e67700-f7cf-11e8-9ede-e7cc0bd55ef9.png)
OK
