### ISSUE TITLE
sheepcoin ,二维码

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/Shpcoin-dev#6]
![image](https://user-images.githubusercontent.com/44828242/48387620-883e5400-e731-11e8-9e8a-47da3d7d0ed7.png)
![image](https://user-images.githubusercontent.com/44828242/48387636-98eeca00-e731-11e8-84e5-0ad5fc348916.png)
![image](https://user-images.githubusercontent.com/44828242/48387838-4661dd80-e732-11e8-8b92-a76512eb226e.png)
![image](https://user-images.githubusercontent.com/44828242/48387852-57125380-e732-11e8-93fb-dac2f240061e.png)

网址：http://www.shpcoin.io/Profile_setting/index?id=125

**Comment by Jvisions** [comment]
我这边二维码显示没有问题啊
