### ISSUE TITLE
手机版，Dashboard profile setting 页面，Email state 

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/Shpcoin-dev#61]
![image](https://user-images.githubusercontent.com/44828242/49357059-efd03980-f708-11e8-9c2f-bcbb2b81e986.png)
![image](https://user-images.githubusercontent.com/44828242/49357114-30c84e00-f709-11e8-8ea9-05b30797c9e9.png)

**Comment by longpizi** [comment]
那是邮箱状态，无法修改，只能看
