### ISSUE TITLE
文章里面要加单引号

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/Shpcoin-dev#67]
![image](https://user-images.githubusercontent.com/44828242/49425399-69832880-f7d8-11e8-84ef-054c368aa074.png)

**Comment by ErisFU** [comment]
![2](https://user-images.githubusercontent.com/41175757/49425662-473dda80-f7d9-11e8-9c70-b2052a012aa8.png)
OK done文章里面要加单引号 #67
