### ISSUE TITLE
Logo layout broken 

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/Shpcoin-dev#7]
![image](https://user-images.githubusercontent.com/44828242/48387991-d6a02280-e732-11e8-8e3c-66f1afebb8e1.png)

网址：http://www.shpcoin.io/Profile_setting/index

**Comment by ErisFU** [comment]
<img width="1177" alt="wx20181113-110953 2x" src="https://user-images.githubusercontent.com/41175757/48388541-ab1e3780-e734-11e8-9cad-648a85157564.png">
okOK！
