### ISSUE TITLE
sheepcoin手机版，layout broken

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/Shpcoin-dev#70]
![image](https://user-images.githubusercontent.com/44828242/49485411-e6181480-f875-11e8-86d8-6f206fb2eb2f.png)
![image](https://user-images.githubusercontent.com/44828242/49485437-0051f280-f876-11e8-9bf4-e49081b270d4.png)
![image](https://user-images.githubusercontent.com/44828242/49485463-152e8600-f876-11e8-86a1-10c168f9b116.png)
![image](https://user-images.githubusercontent.com/44828242/49485489-2bd4dd00-f876-11e8-9d1d-fbd39380d552.png)
![image](https://user-images.githubusercontent.com/44828242/49485565-68a0d400-f876-11e8-969f-5b9b663058da.png)

**Comment by ErisFU** [comment]
![3](https://user-images.githubusercontent.com/41175757/49487905-6db65100-f87f-11e8-8f93-f5bd3b919bf3.png)
![3-1](https://user-images.githubusercontent.com/41175757/49487908-7018ab00-f87f-11e8-8ab9-855fae23c128.png)
![3-2](https://user-images.githubusercontent.com/41175757/49487909-7149d800-f87f-11e8-8ae1-3440faa60db4.png)
OK donne sheepcoin手机版，layout broken #70
![3-4](https://user-images.githubusercontent.com/41175757/49487934-90e10080-f87f-11e8-8c4d-262aa9469d2e.png)
