### ISSUE TITLE
需要修改 Our team “James Elder ”

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/Shpcoin-dev#71]
![image](https://user-images.githubusercontent.com/44828242/49495395-cd235980-f89d-11e8-9957-15081faa2c93.png)

![image](https://user-images.githubusercontent.com/44828242/49495509-2be8d300-f89e-11e8-88b4-90893e14b02a.png)

**Comment by piaoseeun** [comment]
James Elder is a founding member of Sierra Semiconductor. Now PMC-Sierra on Nasdaq

39 Years of Guiding, Managing Public & Private Companies in Europe & Asia: Colt Industries, Axel Johnson Group, Hewlett Packard, Ogilvy & Mather.

22 Years of Experience Launching New Business Ventures, Establishing Joint Venture, Growing Technology & Listing Companies on the London Stock Exchange (AIM). MBA Boston University

**Comment by ErisFU** [comment]
![1](https://user-images.githubusercontent.com/41175757/49632352-58ccef80-fa30-11e8-82c7-5d17cbd4e6e4.png)
需要修改 Our team “James Elder ” #71
