### ISSUE TITLE
our team ，把图片的多余部分去掉一下

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/Shpcoin-dev#72]
![image](https://user-images.githubusercontent.com/44828242/49495547-48850b00-f89e-11e8-8670-497b90ca03e2.png)

**Comment by ErisFU** [comment]
![1](https://user-images.githubusercontent.com/41175757/49632100-7d749780-fa2f-11e8-8f8c-43890bb60050.png)
our team ，把图片的多余部分去掉一下 #72
