### ISSUE TITLE
首页需要修改

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/Shpcoin-dev#73]
![image](https://user-images.githubusercontent.com/44828242/49495634-a0237680-f89e-11e8-9d9f-1721541327a7.png)

1-1 句子改成"Early Backer is Live: 35% Bonus!"
1-2 位置和倒计时近一点
1-3 字大小，大一点
1-4 颜色改成黄色
2. 按钮（login, sign up->white paper, buy token)

**Comment by ErisFU** [comment]
![1](https://user-images.githubusercontent.com/41175757/49632039-469e8180-fa2f-11e8-8245-8209ccb01d23.png)
OK 首页需要修改 #73
