### ISSUE TITLE
点击收藏按钮，显示提示框里按钮颜色

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/Shpcoin-dev#75]
![image](https://user-images.githubusercontent.com/44828242/49500568-f4812300-f8ab-11e8-873e-8c4e6abe26e4.png)
![image](https://user-images.githubusercontent.com/44828242/49500635-1d091d00-f8ac-11e8-9173-7935de4035d2.png)

**Comment by ErisFU** [comment]
![1](https://user-images.githubusercontent.com/41175757/49503099-9a835c00-f8b1-11e8-95c1-99afa5362a34.png)
OK点击收藏按钮，显示提示框里按钮颜色 #75
