### ISSUE TITLE
手机版，头部

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/Shpcoin-dev#77]
![image](https://user-images.githubusercontent.com/44828242/49505307-71b19580-f8b6-11e8-96bc-afea0a40fca0.png)

**Comment by ErisFU** [comment]
![1](https://user-images.githubusercontent.com/41175757/49631774-45208980-fa2e-11e8-89bb-8b103bc9c869.png)
再点击一下按钮隐藏弹出
