### ISSUE TITLE
手机版，位置调整一下，放在中间位置

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/Shpcoin-dev#78]
![image](https://user-images.githubusercontent.com/44828242/49505419-b2a9aa00-f8b6-11e8-9952-3c01164c52ab.png)

**Comment by ErisFU** [comment]
切换手机端后，刷新页面再点按钮，窗户就会自动居中了

**Comment by ErisFU** [comment]
![1](https://user-images.githubusercontent.com/41175757/49626558-5b6e1b80-fa15-11e8-869a-e2021d87ffa4.png)
