### ISSUE TITLE
手机版，字号，小一点

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/Shpcoin-dev#79]
![image](https://user-images.githubusercontent.com/44828242/49506083-20a2a100-f8b8-11e8-8d18-0550ae4fb195.png)

**Comment by ErisFU** [comment]
![1](https://user-images.githubusercontent.com/41175757/49626461-f31f3a00-fa14-11e8-821e-d300e2885fce.png)
![2](https://user-images.githubusercontent.com/41175757/49626463-f4e8fd80-fa14-11e8-9c61-bfa66312a5f5.png)
手机版，字号，小一点 #79
