### ISSUE TITLE
What is Sheepcoin 

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/Shpcoin-dev#81]
![image](https://user-images.githubusercontent.com/44828242/49555495-0b228b00-f93b-11e8-80a4-b4eb25d0b0f3.png)

1.Add the word “the”  … is designed for THE international
2.Add the letter “s” … will be traded with SheepcoinS 
3.Delete period ( . ) at the end of the sentence

**Comment by ErisFU** [comment]
![1](https://user-images.githubusercontent.com/41175757/49625756-c6b5ee80-fa11-11e8-83d0-dd18d0d78e75.png)
What is Sheepcoin #81
