### ISSUE TITLE
如下所示

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/Shpcoin-dev#82]
![image](https://user-images.githubusercontent.com/44828242/49555618-779d8a00-f93b-11e8-81b1-9484a1daa8e7.png)

**Comment by ErisFU** [comment]
![1](https://user-images.githubusercontent.com/41175757/49625557-fb757600-fa10-11e8-8c1b-134c271eb1fd.png)
![2](https://user-images.githubusercontent.com/41175757/49625558-fc0e0c80-fa10-11e8-84dd-bd30721e19cb.png)
![3](https://user-images.githubusercontent.com/41175757/49625560-fe706680-fa10-11e8-9d8d-99a6075a8b3c.png)
如下所示 #82
