### ISSUE TITLE
每次都是先显示一个错位的页面，然后才变成正常的页面，看看如何直接显示正常的页面

### ISSUE THREAD

**Issue by yellmi1983** [MemberSheep-Project/Shpcoin-dev#84]
![image](https://user-images.githubusercontent.com/29912212/49562974-bb52bc80-f958-11e8-81a1-392716f68551.png)
![image](https://user-images.githubusercontent.com/29912212/49562981-c279ca80-f958-11e8-844a-8805bc7d7a6b.png)

**Comment by ErisFU** [comment]
每次都是先显示一个错位的页面，然后才变成正常的页面，看看如何直接显示正常的页面 #84
