### ISSUE TITLE
首页下部，需要修改

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/Shpcoin-dev#86]
![image](https://user-images.githubusercontent.com/44828242/49572120-0e873800-f976-11e8-9eef-a53baba9f5ac.png)
![image](https://user-images.githubusercontent.com/44828242/49572287-67ef6700-f976-11e8-96d5-08ea5f188bdb.png)

1.颜色要改成黑色
2. 按钮样子需要修改

**Comment by ErisFU** [comment]
![1](https://user-images.githubusercontent.com/41175757/49624813-ea773580-fa0d-11e8-9e76-955957f9e002.png)
![2](https://user-images.githubusercontent.com/41175757/49624814-ea773580-fa0d-11e8-991a-530c0e0f2c0e.png)
首页下部，需要修改 #86
