### ISSUE TITLE
需要连接到电商注册页面

### ISSUE THREAD

**Issue by piaoseeun** [MemberSheep-Project/Shpcoin-dev#87]
![image](https://user-images.githubusercontent.com/44828242/49622285-e514ed80-fa03-11e8-9af0-a16d035d0f07.png)
![image](https://user-images.githubusercontent.com/44828242/49622336-1f7e8a80-fa04-11e8-8a50-c22603ae1fc4.png)

**Comment by longpizi** [comment]
因为你已经登录了 ，所以会跳转到首页
