### ISSUE TITLE
sheep coin的回到顶部按钮和底部横条颜色不为黑色，按钮在页面开始滑动时才出现，且删掉横条时，按钮自动掉到底部

### ISSUE THREAD

**Issue by Amber-Lily** [MemberSheep-Project/Shpcoin-dev#89]
![image](https://user-images.githubusercontent.com/41175158/49708215-a7b19980-fc69-11e8-982a-8659d26587bd.png)

**Comment by ErisFU** [comment]
OK l  DONEsheep coin的回到顶部按钮和底部横条颜色不为黑色，按钮在页面开始滑动时才出现，且删掉横条时，按钮自动掉到底部 #89
