### ISSUE TITLE
转账时加链接，弹出条款信息

### ISSUE THREAD

**Issue by yellmi1983** [MemberSheep-Project/Shpcoin-dev#90]
![image](https://user-images.githubusercontent.com/29912212/50068703-d8617800-0201-11e9-8148-cfaea3ac0fc1.png)

**Comment by yellmi1983** [comment]
http://www.shpcoin.io/assets/pdf/Terms_and_Conditions_of_Sheep_Coin_membersheep_company.pdf

**Comment by ErisFU** [comment]
![1](https://user-images.githubusercontent.com/41175757/50074869-313c0b00-0218-11e9-83b2-06fdbb2fae2d.png)
转账时加链接，弹出条款信息 #90
