### ISSUE TITLE
付款页面调整

### ISSUE THREAD

**Issue by yellmi1983** [MemberSheep-Project/Shpcoin-dev#91]
![image](https://user-images.githubusercontent.com/29912212/50068914-adc3ef00-0202-11e9-8bd8-ed8a14678f47.png)

**Comment by yellmi1983** [comment]
点击Pay with Bitcoin弹出来的页面也要类似修改

**Comment by ErisFU** [comment]
![1](https://user-images.githubusercontent.com/41175757/50137693-f056fb80-02d6-11e9-8c18-0ed29057b6ee.png)
付款页面调整 #91
